Add Admonitions and a Document section
haotian2006/MyDocs pull request #23
Opened 2024-08-03 04:32 UTC by haotian2006

Added Admonis 
![image](https://github.com/user-attachments/assets/b04c9a6a-d7d3-4600-b674-3896408f9cfe)
![image](https://github.com/user-attachments/assets/1d4369db-5bef-4fb4-8457-e7de459b7217)

2024-08-03 04:43 UTC, haotian2006 commented
@cyrus01337 for some reason the formatter thinks there's a syntax error in the mdx and pastor file and I'm unsure how to fix it

2024-08-03 13:42 UTC, cyrus01337 commented
Hmm, very strange, and your current files don't show what it's complaining about either. I'll take a look.

2024-08-03 17:17 UTC, cyrus01337 requested changes
The MDX files can be formatted via `npm run format`, you can verify that the project is formatted via `npm run lint:formatting`. The pipeline will always tell you if you haven't formatted your current changes, hence the error from before.

2024-08-03 17:17 UTC, cyrus01337 commented on src/components/Aside.astro
> +    </div>
Remove - there's no 2nd div, causing invalid HTML.

2024-08-03 17:17 UTC, cyrus01337 commented on src/components/Aside.astro
> +    </div>
Remove - there's no 2nd div, causing invalid HTML.

2024-08-04 00:32 UTC, cyrus01337 approved these changes
These look so cool.

2024-08-04 04:43 UTC, merged