Display DIscord Avatars
haotian2006/MyDocs pull request #8
Opened 2024-07-21 10:31 UTC by haotian2006

Created a system that can retrieve a person's discord avatar and username from userid. 

![image](https://github.com/user-attachments/assets/22e2f768-d71e-4358-ab42-4c903bbea4db)

![image](https://github.com/user-attachments/assets/ab1d1af3-f167-4ba8-8209-1942a318b60d)

probably gonna make changes to how it's displayed and change how the data is stored since right now its just stored in the config 

![image](https://github.com/user-attachments/assets/c181b7dd-6732-47c1-816e-0346ea7fb63e)

2024-07-22 04:00 UTC, haotian2006 commented
Changed it so you can only put 1 author field that is either discord github or neither

"discord: userid"
![image](https://github.com/user-attachments/assets/a08e5250-c522-4c92-8e42-15f684851280)

"github: userid"
![image](https://github.com/user-attachments/assets/427bdc8c-665f-4a8f-a6bd-34d62b0854d6)

"Name"
![image](https://github.com/user-attachments/assets/a79bc9e7-c12f-4a54-87da-17b44fe16ae2)

2024-07-23 08:38 UTC, cyrus01337 commented
Great work on this so far, I'll take a look at lunch/after work.

2024-07-24 04:25 UTC, cyrus01337 requested changes
File changes were not auto-formatted, most likely due to lack of editor configuration. This was resolved in the devcontainer instance exclusively, though I've neglected non-devcontainer VS Code instances without realising.

~I plan to resolve that matter separately~ (see #9), in the mean time you should run `<package-manager> run format` and commit the changes.

2024-07-24 04:25 UTC, cyrus01337 commented on src/content/config.ts
> +        author_data: zod.record(zod.unknown()).optional(),
## TL;DR: `config.ts` (bad name by Astro, will look into) defines properties in MDX files. `author_data` isn't shown to be used anywhere but `src/pages/[...slug].astro`, so it should be a type in that file or a different file.

Admittedly, `config.ts` isn't the most descriptive name that Astro has picked. This file determines what you an expect in MDX files within [`src/content/documents`](https://github.com/haotian2006/MyDocs/tree/Integrate-DiscordAPI/src/content/documents), so `author_data` which is not defined in other MDX files and is exclusively used in `src/pages/[...slug].astro` should be a type and either be placed there or shoved into a separate file altogether. I'll see if we can't choose a more apt name separately.

2024-07-24 04:25 UTC, cyrus01337 commented on src/pages/[...slug].astro
> +            { (entry.data.author_data as {url:string}).url &&(
The initial opening parentheses `(` was never closed, causing a syntax error. Please remove.

2024-07-24 04:25 UTC, cyrus01337 commented on src/pages/[...slug].astro
> +export const githubCache = new Map<string,{username:string,pfp:string,url:string}|undefined>();
Use `T | null` as `Map<T>.get(...)` returns `T | undefined` - `null` should be used as the special-case value. This is detailed in a separate comment further into the file.

2024-07-24 04:25 UTC, cyrus01337 commented on src/pages/[...slug].astro
> +  }
If fetching the avatar fails i.e when a user doesn't exist, the cache entry will remain `undefined`, which will allow for repeat API calls. `null` could be used to special-case this and avoid the situation entirely.

2024-07-24 07:40 UTC, haotian2006 commented on src/pages/[...slug].astro
> +export const githubCache = new Map<string,{username:string,pfp:string,url:string}|undefined>();
for some reason when I run without the export it says it doesn't exists

2024-07-24 07:40 UTC, haotian2006 commented on src/pages/[...slug].astro
> +export const githubCache = new Map<string,{username:string,pfp:string,url:string}|undefined>();
and putting an export seems to fix that

2024-07-24 07:42 UTC, haotian2006 commented on src/pages/[...slug].astro
> +export const githubCache = new Map<string,{username:string,pfp:string,url:string}|undefined>();
![image](https://github.com/user-attachments/assets/0964b099-b141-484e-96d9-7f578077d3aa)

2024-07-24 11:16 UTC, cyrus01337 commented on src/pages/[...slug].astro
> +export const githubCache = new Map<string,{username:string,pfp:string,url:string}|undefined>();
Strange, I can't seem to reproduce this in the devcontainer setup, try replicating this using the devcontainer setup. Also, what command are you using to run this?

2024-07-24 11:35 UTC, cyrus01337 commented on src/pages/[...slug].astro
> +export const githubCache = new Map<string,{username:string,pfp:string,url:string}|undefined>();
When `getStaticPaths` is called, it doesn't take in the top-level/global variables defined. A workaround is hoisting the variables by exporting them from a separate module, which you import in this file, guaranteeing the values are top-level.

I recommend asking in the Astro server what the cause could be as this doesn't make immediate sense why this behaviour would occur.

2024-07-25 06:21 UTC, cyrus01337 commented
If you're struggling to avoid tracking  `.astro/` by the way, you should be able to run `git rm --cached .astro/` which will tell Git to stop tracking it while keeping the files intact on your filesystem.

2024-07-29 08:35 UTC, cyrus01337 approved these changes
Great work on this. :slightly_smiling_face:

2024-07-29 08:38 UTC, merged